### ISSUE TITLE
Optional reclustering of AK8 jets

### ISSUE THREAD

**Issue by rappoccio** [cmsb2g/B2GAnaFW#19]
To run some new advanced background estimates, we need lower-pt AK8 jets (pt > 40 && pt < 200). I need to add an optional reclustering configuration parameter if needed for some limited samples.

**Comment by decosa** [comment]
Hi Sal,

We are applying minimal changes right now to two new development branches (not yet announced):

CMSSW_7_4_X_V6_25ns
CMSSW_7_4_X_V6_50ns


This is a temporary solution for having a working version for both dataset, includes fixes to electron id and changed to electron ID for 25 ns.
Muon Id for 25 ns is still missing. It will be added most likely tomorrow.
There is a discussion ongoing for merging the two at certain point.

Do you wish to include the optional reclustering already now? I think this is a good moment.

We were planning to release a tag for production by the end of this week.

Annapaola

On 23 Sep 2015, at 17:32, rappoccio <notifications@github.com<mailto:notifications@github.com>> wrote:


To run some new advanced background estimates, we need lower-pt AK8 jets (pt > 40 && pt < 200). I need to add an optional reclustering configuration parameter if needed for some limited samples.

**Comment by rappoccio** [comment]
Hi, Annapaola,

This one is a special case so I would prefer to wait until something is stable. The other Issue I opened (HEEP ID) is a better candidate for this week's release.

Cheers,
Sal

**Comment by decosa** [comment]
Hi Sal,

Ok, I think that you can go ahead as soon as you are ready and let Deborah know when you are done.
She will then include changes to muonID if needed.

Cheers,

Annapaola


On 23 Sep 2015, at 17:46, rappoccio <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, Annapaola,

This one is a special case so I would prefer to wait until something is stable. The other Issue I opened (HEEP ID) is a better candidate for this week's release.

Cheers,
Sal

**Comment by rappoccio** [comment]
Hi, Annapaola,

OK will do!

Cheers,
Sal

**Comment by rappoccio** [comment]
Hi, Annapaola,

I think I can also take the opportunity to use the new VID as well. I will add that too.

Cheers,
Sal

**Comment by decosa** [comment]
Hi Sal,

That would be great.
This point was actually under discussion in a separate thread, we were talking about including VID.
Savvas was going to investigate with Egamma people if it is possible to disentangle the isolation and the ID.
Do you know if this is the case?

Thanks,

Annapaola

On 23 Sep 2015, at 18:47, rappoccio <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, Annapaola,

I think I can also take the opportunity to use the new VID as well. I will add that too.

Cheers,
Sal

**Comment by rappoccio** [comment]
OK just to make it clear on this thread too : now done with VID, 7.4.12 or later is required.

https://github.com/cmsb2g/B2GAnaFW/commit/88d28e6a16f9736c9bb5c0e3bd0c6a765fb902c0
