### ISSUE TITLE
Need to merge to master

### ISSUE THREAD

**Issue by rappoccio** [cmsb2g/B2GAnaFW#20]
@dmajumder, there is one commit that will not merge to master (https://github.com/cmsb2g/B2GAnaFW/commit/b8bb2696d7b281ace8064921eb0c04dea83d7214). This needs to be merged to master so we can make the next couple of releases. 

Thanks,
Sal

**Comment by dmajumder** [comment]
@rappoccio done. Can we delete "CMSSW_7_4_12" or you want to wait to validate with the new CMSSW_7_4_12 samples?

**Comment by rappoccio** [comment]
Thanks Devdatta! We can delete the other branch, sure.

**Comment by decosa** [comment]
Hi all,

I don’t think having the 7_4_12 in the master is a good idea.
This is the branch for the reprocessed miniAOD which are under validation.
Of course all the improvements in terms of cleaning should go in the master,
but I don’t think this is the case for those aspects which are specific to reprocessed miniAOD.

We shall probably have a chat to define the policy of what shall go in the master and what not.
And also decide how to handle the three scenarios: 25 ns, 50 ns and new 25 ns.

Cheers,

Annapaola




On 24 Sep 2015, at 14:54, dmajumder <notifications@github.com<mailto:notifications@github.com>> wrote:


@rappoccio<https://github.com/rappoccio> done. Can we delete "CMSSW_7_4_12" or you want to wait to validate with the new CMSSW_7_4_12 samples?

**Comment by rappoccio** [comment]
Hi, Annapaola,

Hmm, good point. But maybe I'm confused a bit, I thought that anything for 7_4_12 was also applicable to future releases? Maybe we could have : 

master : 7_4_12 and 75x
74x branches : for < 7_4_12

?

Cheers,
Sal

**Comment by decosa** [comment]
Hi Sal,



On 24 Sep 2015, at 15:33, rappoccio <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, Annapaola,

Hmm, good point. But maybe I'm confused a bit, I thought that anything for 7_4_12 was also applicable to future releases? Maybe we could have :

master : 7_4_12 and 75x

If we decide to go in that way it is fine with me, just we need to keep in mind that the master is going to be something
that is not “completely usable at the moment for the analysis”.
What I mean is that we don’t have yet a 4_7_12 production (aside relval and few reprocessing).


74x branches : for < 7_4_12

?


As they are now? Yes, I think this is the unique way to go for the moment.
We should also merge 25 ns and 50 ns branches as soon as we incorporate 25 and 50 ns electron id in a unique module.


Cheers,


Annapaola



Cheers,
Sal

**Comment by dmajumder** [comment]
Hi Sal, Annapaola, 
I understand that we delete CMSSW_7_4_12? I just want to keep branch proliferation in check. ;)

**Comment by rappoccio** [comment]
Yes, this is what I am proposing. Updates will have to be added to all three branches (git cherry-pick and/or git rebase can help with that).

**Comment by dmajumder** [comment]
Hi Sal,

Will do.

Regarding the policy definition Annapaola proposed, I suggested having master as main development branch (separate developments can be created for individual topics, merged to master when ready, and deleted), and create production branches staring from commits on master. We make tags on the production branches, and only bug-fixes allowed on these branches.
I think this is similar to the plan you had in mind.

**Comment by rappoccio** [comment]
That's about right, yes. The stable branches are as we currently have them. It does get annoying if we have new features we want to backport, but this is the same model as CMSSW.
