### ISSUE TITLE
Invalid tool Utilities/Timing

### ISSUE THREAD

**Issue by TC01** [cmsb2g/B2GAnaFW#27]
When running ```scram build```, I get this message:

```
****WARNING: Invalid tool Utilities/Timing. Please fix src/Analysis/B2GAnaFW/BuildFile.xml file.
```

Looks like Utilities/Timing doesn't exist in CMSSW_7_4_X? This is obviously not a serious warning, because stuff still works and nothing seems to try to invoke Utilities/Timing stuff.

**Comment by dmajumder** [comment]
removed.
