### ISSUE TITLE
New production tag for 76X

### ISSUE THREAD

**Issue by dmajumder** [cmsb2g/B2GAnaFW#39]
@alefisico @jkarancs @decosa @skyriacoCMS 
A new tag created for 76X production https://github.com/cmsb2g/B2GAnaFW/tree/v7.6.x_v1.0
Anybody to check if the instructions are correct before announcing, by today?

**Comment by alefisico** [comment]
I just tested the instructions and found an small bug, I created the PR #40 . After that, the instructions are correct.
