### ISSUE TITLE
L2L3Residual corrections missing from T1 MET

### ISSUE THREAD

**Issue by oiorio** [cmsb2g/B2GAnaFW#67]
Currently when we do T1MET corrections on data we do remove the contribution of L2L3Residuals as default option(forceResiduals=True):

https://github.com/cmsb2g/B2GAnaFW/blob/v8.0.x_v2.4/test/b2gedmntuples_cfg.py#L595-L612

Need to check whether we should leave them in instead, an if such is the case, take out the above lines.

* Update: needs to be changed, either removing it entirely or changing it so it's not default

**Comment by dmajumder** [comment]
I guess this is now settled with the latest changes and v8.0.x_v2.5, so I am closing it.
