### ISSUE TITLE
Creating new tag v8.0.x_v2.5

### ISSUE THREAD

**Issue by alefisico** [cmsb2g/B2GAnaFW#69]
Let's move the developers conversation here :)
So can all of you mention what you have included in this version? 
From my side I will include a new version of the jetToolbox, which does not change content but improves some performance. 
Also, when do you think is reasonable to have a new tag.

**Comment by alefisico** [comment]
Just calling contributors @dmajumder @skyriacoCMS @oiorio @jkarancs (please include however you think should be in the thread)

**Comment by oiorio** [comment]
From my side, I added the Moriond JEC , MET T1 was also fixed so now it is correctly recalculated on the fly with the met recipe for 8_0_26_patch1.

We should also update the README so that it reflects the fact that 

git cms-merge-topic ikrav:egm_id_80X_v2

is not needed and it all needs to be run on top of 8_0_26_patch1.

**Comment by alefisico** [comment]
I prepare a first draft of the README file: https://github.com/alefisico/B2GAnaFW/blob/CMSSW_8_0_X_V2/README.md
Is there something else to add or wrong?
We need to change the version of the toolbox and the tag, but we can do it later.

**Comment by oiorio** [comment]
@skyriacoCMS Do we need to keep the following part regardless of the git cms-merge-topic ikrav:egm_id_80X_v2 not being there for the egamma wprking points?

cd $CMSSW_BASE/external/slc6_amd64_gcc530

git clone git@github.com:ikrav/RecoEgamma-ElectronIdentification.git data/RecoEgamma/ElectronIdentification/data

cd data/RecoEgamma/ElectronIdentification/data

git checkout egm_id_80X_v1

cd $CMSSW_BASE/src

**Comment by oiorio** [comment]
Hi Again! I checked myself the electron vid veto and tight on a MC sample and on a run b sample.

They give the same result with and without the piece above, both in the root file and in the .py dumped file, so I think we should be fine with the above recipe from @alefisico, sorry for the being so pedantic!

**Comment by alefisico** [comment]
I thought that you send the message before you received the email saying that we don't need it. But ok, extra confirmation is always better. :D

**Comment by alefisico** [comment]
I thought that you send the message before you received the email saying that we don't need it. But ok, extra confirmation is always better. :D
We are almost ready I think. @skyriacoCMS is adding some photon variables and I think after that we are ready for a new tag, what do you think @dmajumder?

**Comment by dmajumder** [comment]
I think we are almost ready.  @skyriacoCMS , any chances of the MVA electron ID getting added?

**Comment by dmajumder** [comment]
@alefisico @oiorio @jkarancs @skyriacoCMS do we wait for this 
https://hypernews.cern.ch/HyperNews/CMS/get/b2g/995.html?

**Comment by alefisico** [comment]
I was about to ask this, do we have any deadlines? I mean by when do we want to launch the next tag? When is the rerererererereco :joy: ready?

**Comment by oiorio** [comment]
I can't say what modification is needed, and if there is something that we should do with much care.

My2c: I'd go for a tag as it is now and follow up whenever we manage to run on the ReReReco. 

From the top side, we do have some jobs to launch asap, but it's a weak argument, we can do it even with a non-committed release if it's deemed necessary to run on the Re^3co.

**Comment by dmajumder** [comment]
@oiorio If there is an immediate use case, we should make a tag of course.
The development for the re-re-₹...reco could happen later. Maybe start a branch CMSSW_8_0_X_V3?

**Comment by oiorio** [comment]
I'd second that! I guess this is far from being the end of the story for the development on top of the ReReco, making a new branch could be worth it.

**Comment by alefisico** [comment]
:+1: fine for me

**Comment by skyriacoCMS** [comment]
Hello guys, 

I m also working on some changes. I see that you will have a re-re-reco version coming on later on. So I would have that in mind as a target for the things I am working on. 

0) Changes to the PhotonJets collection that I am planning a while now. 
1) will be the MVA ID devdatta mentioned. 
2) Photon IDs are old and useless. I need to add the Moriond versions at least - unfortunately they are not part of the release as the electron IDs are. 

So yeah If you proceed, all is fine with me. 

Cheers

**Comment by dmajumder** [comment]
OK, so anybody volunteers to cut a new v8.0.x_v2.5 tag? I see that the README is already updated.

**Comment by alefisico** [comment]
ok, talking privately with @skyriacoCMS I think he is very close to finish some of the items in the todo list. So, I propose to wait until Monday and then, if you want, I can create the new tag and send the email.
Anyway, even if we release it today, I dont think people will start ntuplizing it now. 
Comments?

**Comment by oiorio** [comment]
Well, I would indeed start, but I see the point :) Let's keep Monday as deadline for any further additions, I seem to understand that not all of it would be ready anyways.

**Comment by dmajumder** [comment]
@oiorio if you want to start and do not need the items from Savvas, I think we should have a tag released for you. We can then get the new developments for the re-MINIAOD since I feel we may need a tag for that ASAP.

**Comment by oiorio** [comment]
@dmajumder  I don't need those items, so I can start right away tbh, that would be very helpful. I should still have the possibility able to do that myself, right?

**Comment by dmajumder** [comment]
@oiorio certainly. Just thinking that a tag is good for tracking, if that's important for you.

**Comment by oiorio** [comment]
Done! CMSSW_8_0_X_V2 updated with Alejandro's readme and tag v2.5 added.

**Comment by dmajumder** [comment]
Thanks a lot! Can you have a look at the release
https://github.com/cmsb2g/B2GAnaFW/releases/tag/untagged-296e11d3eb7dab7f3002
to see if this looks OK

**Comment by oiorio** [comment]
Looks good! Thanks!

**Comment by dmajumder** [comment]
I have published the release and updated the TWikihttps://twiki.cern.ch/twiki/bin/view/CMS/B2GAnalysisFwk#CMSSW_8_0_X
I think one you should announce it to the HN, you guys did all the work.
Also, please make it clear that this tag is intended for special cases, and not for mass re-ntuplizing the re-reco data or the Summer16 MC. A new tag for the re-MiniAOD (03Feb2017) will be produced later.
Thanks a lot!

**Comment by dmajumder** [comment]
Thanks @oiorio
